version: '3'
services:
  # mysql
  geekai-mysql:
    image: crpi-1rhmnyrson8h7iaj.ap-southeast-1.personal.cr.aliyuncs.com/charles_jan/mysql:8.0.33
    container_name: dapianke-mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=mhSCk0NheGhmtsha
    ports:
      - '3307:3306'
    volumes:
      - ./conf/mysql/my.cnf:/etc/mysql/my.cnf
      - ./data/mysql/data:/var/lib/mysql
      - ./logs/mysql:/var/log/mysql
      - ./data/mysql/init.d:/docker-entrypoint-initdb.d/
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 5s
      timeout: 10s
      retries: 10

  # redis
  geekai-redis:
    image: crpi-1rhmnyrson8h7iaj.ap-southeast-1.personal.cr.aliyuncs.com/charles_jan/redis:6.0.6
    restart: always
    container_name: dapianke-redis
    command: redis-server --requirepass mhSCk0NheGhmtsha
    volumes:
      - ./data/redis:/data
    ports:
      - '6380:6379'
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 3s
      timeout: 10s
      retries: 5

  #  xxl-job-admin:
  #    container_name: geekai-xxl-job-admin
  #    image: crpi-1rhmnyrson8h7iaj.ap-southeast-1.personal.cr.aliyuncs.com/charles_jan/xxl-job-admin:2.4.0
  #    restart: always
  #    ports:
  #      - "8081:8080"
  #    environment:
  #      - PARAMS=--spring.config.location=/application.properties
  #    volumes:
  #      - ./logs/xxl-job:/data/applogs
  #      - ./conf/xxl-job/application.properties:/application.properties

  tika:
    image: crpi-1rhmnyrson8h7iaj.ap-southeast-1.personal.cr.aliyuncs.com/charles_jan/tika:latest
    container_name: dapianke-tika
    restart: always
    ports:
      - '9998:9998'

  #  midjourney-proxy:
  #    image: crpi-1rhmnyrson8h7iaj.ap-southeast-1.personal.cr.aliyuncs.com/charles_jan/midjourney-proxy:2.6.2
  #    container_name: geekai-midjourney-proxy
  #    restart: always
  #    ports:
  #      - "8082:8080"
  #    volumes:
  #      - ./conf/mj-proxy:/home/spring/config

  # 后端 API 程序
  geekai-api:
    image: crpi-1rhmnyrson8h7iaj.ap-southeast-1.personal.cr.aliyuncs.com/charles_jan/geekai-api:v4.1.10-amd64
    container_name: dapianke-api
    restart: always
    depends_on:
      geekai-mysql:
        condition: service_healthy
      geekai-redis:
        condition: service_healthy
    environment:
      - DEBUG=false
      - LOG_LEVEL=info
      - CONFIG_FILE=config.toml
    ports:
      - '5678:5678'
      - '9999:9999'
    volumes:
      - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime
      - ./conf/config.toml:/var/www/app/config.toml
      - ./logs/app:/var/www/app/logs
      - ./static:/var/www/app/static
      - ./data/leveldb:/var/www/app/data
      - ./certs:/var/www/app/certs

  # 前端应用
  geekai-web:
    image: crpi-1rhmnyrson8h7iaj.ap-southeast-1.personal.cr.aliyuncs.com/charles_jan/geekai-web:v4.1.10-amd64
    container_name: dapianke-web
    restart: always
    depends_on:
      - geekai-api
    ports:
      - '80:8080'
      - '443:443'
      - '8080:8080'
    volumes:
      - ./logs/nginx:/var/log/nginx
      - ./conf/nginx/conf.d:/etc/nginx/conf.d
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/nginx/ssl:/etc/nginx/ssl
